---
- name: Copy file and install cronjob
  hosts: servers  # Replace with your target host
    #become: yes  # Enable privilege escalation

  vars:
    file_to_copy: files/checkin.py  # Replace with the file you want to copy
    destination_directory: /home/user/checkin  # Replace with the directory on the remote host where you want to copy the file
    cron_job: "*/2 * * * * /usr/bin/python3 /home/user/checkin/checkin.py"  # Replace with the command you want to run every 2 minutes

  tasks:
    - name: Copy file to remote host
      copy:
        src: "{{ file_to_copy }}"
        dest: "{{ destination_directory }}/"

    - name: Add cronjob
      cron:
        name: "Run checkin scipt"
        minute: "*/2"
        job: "/usr/bin/python3 /home/user/checkin/checkin.py"
