---
- name: Copy file and install cronjob
  hosts: servers  # Replace with your target host
    #become: yes  # Enable privilege escalation

  vars_files:
    - vars/config.vars
    
  tasks:
    - name: Copy file to remote host
      copy:
        src: "{{ file_to_copy }}"
        dest: "{{ destination_directory }}/"

    - name: Add cronjob
      cron:
        name: "Run checkin scipt"
        minute: "*/2"
        job: "/usr/bin/python3 /home/miles/checkin/checkin.py"
