name: .NET

on:
  push:
    branches: [ ci, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --project Checkin.Api
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Setup auth
      run: export CR_PAT=${{ secrets.DOCKER_TOKEN }}
    - name: Authenticate with repository
      run: echo $CR_PAT | docker login ghcr.io -u halemiles --password-stdin 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${IMAGE_NAME}
    - name: Push image
      run: docker push ${REGISTRY} %{IMAGE_NAME} 
    - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # optionally push to the Docker Hub (docker.io)
          # docker_io_token: ${{ secrets.DOCKER_IO_ACCESS_TOKEN }}
